Repository redelivre/login-cidadao, pull requests merged in 2018-08, with the labels that each got.

#279 Fixed Remote Claim Parser
  src/LoginCidadao/RemoteClaimsBundle/Entity/RemoteClaim.php
  src/LoginCidadao/RemoteClaimsBundle/Parser/RemoteClaimParser.php
  src/LoginCidadao/RemoteClaimsBundle/Tests/Parser/RemoteClaimParserTest.php
Labels: bug, in progress

#280 Fixed implicit authorization generation
  src/LoginCidadao/CoreBundle/Entity/Authorization.php
  src/LoginCidadao/CoreBundle/Resources/config/services.yml
  src/LoginCidadao/CoreBundle/Service/AuthorizationManager.php
  src/LoginCidadao/CoreBundle/Tests/Service/AuthorizationManagerTest.php
  src/LoginCidadao/RemoteClaimsBundle/Controller/RemoteClaimController.php
  src/LoginCidadao/RemoteClaimsBundle/Entity/RemoteClaim.php
  src/LoginCidadao/RemoteClaimsBundle/Model/RemoteClaimManager.php
  src/LoginCidadao/RemoteClaimsBundle/Model/RemoteClaimManagerInterface.php
  src/LoginCidadao/RemoteClaimsBundle/Resources/config/services.yml
  src/LoginCidadao/RemoteClaimsBundle/Tests/Model/RemoteClaimManagerTest.php
Labels: bug, in progress

#281 Updated dependencies
  composer.lock
Labels: bug, in progress

#282 fixed trusted headers issue
  web/app.php
  web/app_dev.php
Labels: in progress

#283 app.php cleaned up
  web/app.php
Labels: in progress

#287 Fixed CORS settings for Implicit Flow
  app/config/config.yml
Labels: bug, in progress

#285 add Screenshot and Update README,
  README.md
  screenshots/0.png
  screenshots/1.png
Labels: in progress

#288 Upgrade to Symfony 3.4
  .travis.yml
  app/AppKernel.php
  app/SymfonyRequirements.php
  app/check.php
  app/config/config.yml
  app/config/parameters.yml.dist
  app/config/parameters.yml.vagrant
  app/config/routing_dev.yml
  app/console
  composer.json
  composer.lock
  phpunit.xml.dist
  src/LoginCidadao/APIBundle/Resources/config/services.yml
  src/LoginCidadao/CoreBundle/Command/MobileCleanupCommand.php
  src/LoginCidadao/CoreBundle/Command/PopulateDatabaseCommand.php
  src/LoginCidadao/CoreBundle/Controller/Admin/PersonController.php
  src/LoginCidadao/CoreBundle/Controller/AuthorizationController.php
  src/LoginCidadao/CoreBundle/Controller/TwoFactorAuthenticationController.php
  src/LoginCidadao/CoreBundle/Entity/Person.php
  src/LoginCidadao/CoreBundle/EventListener/PersonSerializeEventListener.php
  src/LoginCidadao/CoreBundle/Form/ImpersonationReportType.php
  src/LoginCidadao/CoreBundle/Form/Type/ClientBaseFormType.php
  src/LoginCidadao/CoreBundle/Form/Type/ClientFormType.php
  src/LoginCidadao/CoreBundle/Form/Type/CommonFormType.php
  src/LoginCidadao/CoreBundle/Form/Type/CountrySelectorComboType.php
  src/LoginCidadao/CoreBundle/Form/Type/PersonResumeFormType.php
  src/LoginCidadao/CoreBundle/Form/Type/StateSelectorComboType.php
  src/LoginCidadao/CoreBundle/Model/PersonInterface.php
  src/LoginCidadao/CoreBundle/Resources/config/services.yml
  src/LoginCidadao/CoreBundle/Resources/views/Form/fields.html.twig
  src/LoginCidadao/CoreBundle/Security/User/Provider/FOSUBUserProvider.php
  src/LoginCidadao/CoreBundle/Tests/EventListener/PersonSerializeEventListenerTest.php
  src/LoginCidadao/OAuthBundle/Form/OrganizationType.php
  src/LoginCidadao/OAuthBundle/Model/AccessTokenManager.php
  src/LoginCidadao/OAuthBundle/Resources/config/services.yml
  src/LoginCidadao/OpenIDBundle/Controller/AuthorizeController.php
  src/LoginCidadao/OpenIDBundle/Controller/ClientRegistrationController.php
  src/LoginCidadao/OpenIDBundle/Controller/SessionManagementController.php
  src/LoginCidadao/OpenIDBundle/DependencyInjection/LoginCidadaoOpenIDExtension.php
  src/LoginCidadao/OpenIDBundle/Form/ClientMetadataWebForm.php
  src/LoginCidadao/OpenIDBundle/Tests/Task/CompleteUserInfoTaskValidatorTest.php
  src/LoginCidadao/ValidationControlBundle/Event/IdCardValidateEvent.php
  web/app.php
  web/app_dev.php
Labels: enhancement, in progress

#290 Fixed login form
  src/LoginCidadao/CoreBundle/Form/Type/LoginFormType.php
  src/LoginCidadao/CoreBundle/Tests/Form/Type/LoginFormTypeTest.php
Labels: in progress

#291 updated forms to be compatible with Symfony 3.4
  src/LoginCidadao/CoreBundle/Form/Type/IdCardType.php
  src/LoginCidadao/CoreBundle/Form/Type/SuggestionFilterFormType.php
  src/LoginCidadao/CoreBundle/Form/Type/TelType.php
  src/LoginCidadao/CoreBundle/Form/Type/TwoFactorAuthenticationFormType.php
  src/LoginCidadao/OpenIDBundle/Form/ClientMetadataForm.php
Labels: in progress

#292 fixed forms validation
  src/LoginCidadao/CoreBundle/Form/Type/ClientBaseFormType.php
  src/LoginCidadao/DynamicFormBundle/Controller/FormController.php
  src/LoginCidadao/OpenIDBundle/Controller/ClientRegistrationController.php
Labels: in progress

#293 fixed forms
  src/LoginCidadao/CoreBundle/Controller/IdCardController.php
  src/LoginCidadao/CoreBundle/Form/Type/IdCardType.php
  src/LoginCidadao/CoreBundle/Form/Type/TwoFactorAuthenticationFormType.php
Labels: bug, enhancement, in progress

#295 Organizations forms fixed
  src/LoginCidadao/OAuthBundle/Controller/OrganizationController.php
  src/LoginCidadao/OAuthBundle/Form/OrganizationType.php
Labels: bug, enhancement
